name: Check pipeline for stack

on: workflow_dispatch
#  pull_request:
#    branches:
#      - master
#
#  push:
#    branches:
#      - master

jobs:
  check_stack:
    name: Check Terraform stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: TF init example
        id: init_example
        run: terraform init
        working-directory: examples/

      - name: TF validate example
        id: validate_example
        run: terraform validate
        working-directory: examples/

      # This following action will need to be ported to
      # an internal repo or equivalent process
      - name: Run TFLint on example and report
        id: tflint_example
        uses: reviewdog/action-tflint@master
        with:
          working_directory: "examples"
          tflint_rulesets: "google"
          flags: "--module"

      - name: TF plan example
        id: plan_example
        run: terraform plan -out=tfplan
        working-directory: examples/

      - name: TF show example plan
        id: gen_plan_json
        run: terraform show -json tfplan > ../plan.json
        working-directory: examples/

      - name: Run infracost diff
        uses: infracost/infracost-gh-action@v0.7.0
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: /scripts/ci/diff.sh # Do not change
          path: plan.json

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: examples/

      #- name: Render terraform docs and push changes back to PR
      #  uses: terraform-docs/gh-actions@v0.6.1
      #  with:
      #    working-dir: .
      #    output-file: README.md
      #    output-method: inject
      #    git-push: "true"
