name: Check pipeline for stack

on: workflow_dispatch
#  pull_request:
#    branches:
#      - master
#
#  push:
#    branches:
#      - master

jobs:
  check_stack:
    name: Check Terraform stack
    runs-on: ubuntu-latest
    steps:
      #- name: Set up Cloud SDK
      #  uses: google-github-actions/setup-gcloud@master
      #  with:
      #    project_id: ${{ secrets.GCP_PROJECT_ID }}
      #    service_account_key: ${{ secrets.GCP_SA_KEY }}
      #    export_default_credentials: true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Init example
        id: init_example
        run: terraform -chdir=examples init

      - name: Validate example
        id: validate_example
        run: terraform -chdir=examples validate

      - name: Run TFLint on example and report
        id: tflint_example
        uses: reviewdog/action-tflint@master
        with:
          working_directory: "examples"
          tflint_rulesets: "google"
          flags: "--module"

      #- name: Plan example
      #  id: plan_example
      #  run: terraform -chdir=examples plan

      # The following step runs a Terraform plan
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@v0.7.0
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        with:
          entrypoint: /scripts/ci/diff.sh # Do not change
          path: examples/

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: examples/

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v0.6.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
